config/routes.rb
Rails.application.routes.draw do

  resources :postits

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/postit.rb
class Postit < ApplicationRecord
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/postits_controller.rb
class PostitsController < ApplicationController
  def index
    @postits = Postit.all
  end

  def show
    @postit = Postit.find(params[:id])
  end

  def new
    @postit = Postit.new
  end

  def edit
    @postit = Postit.find(params[:id])
  end

  def create
    @postit = Postit.new(postit_params)

    if @postit.save
      redirect_to @postit
    else
      render 'new'
    end
  end

  def update
    @postit = Postit.find(params[:id])

    if @postit.update(postit_params)
      redirect_to @postit
    else
      render 'edit'
    end
  end

  def destroy
    @postit = Postit.find(params[:id])
    @postit.destroy

    redirect_to postits_path
  end

  def sortable
    @postit = Postit.find(params[:id])
  end

  private
    def postit_params
      params.require(:postit).permit(:title, :text)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/postits_helper.rb
module PostitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trello</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/postits/_form.html.erb
<%= form_for @postit do |f| %>
<script>
var ready;
ready = function(){
// call sortable on our div with the sortable class
$('.sortable').sortable();
}
</script>

  <% if @postit.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@postit.errors.count, "error") %> prohibited
        this postit from being saved:
      </h2>
      <ul>
        <% @postit.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <body>
    <ul>
      <li>
          <h2>Post-it #1</h2>
          <p>
            <%= f.label :title %><br>
            <%= f.text_field :title %>
          </p>

          <p>
            <%= f.label :text %><br>
            <%= f.text_area :text %>
          </p>

          <p>
            <%= f.submit %>
          </p>

        <% end %>
      </liv>
    </ul>
  </body>

app/views/postits/edit.html.erb
<h1>Edit postit</h1>

<%= render 'form' %>

<%= link_to 'Back', postits_path %>

app/views/postits/index.html.erb
<h1>Here's a List of Your Post-its!</h1>
<%= link_to 'New postit', new_postit_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>

<script>
<link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css"
         rel = "stylesheet">
      <script src = "https://code.jquery.com/jquery-1.10.2.js"></script>
      <script src = "https://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
</script>
<script>
         $(function() {
            $( ".note" ).draggable();
         });
</script>

  <body>
    <div class="note">
      <% @postits.each do |postit| %>
          <ul>
            <li>
                <h2><%= postit.title %></h2>
                <p><%= postit.text %>
                <%= link_to 'Show', postit_path(postit) %>
                <%= link_to 'Edit', edit_postit_path(postit) %>
                <%= link_to 'Destroy', postit_path(postit),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %>
                </p>
            </li>
          </ul>
    </div>
  <% end %>
</body>

app/views/postits/new.html.erb
<h1>New postit</h1>

<%= render 'form' %>

<%= link_to 'Back', postits_path %>

app/views/postits/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @postit.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @postit.text %>
</p>

<%= link_to 'Edit', edit_postit_path(@postit) %> |
<%= link_to 'Back', postits_path %>

app/views/welcome/index.html.erb
<h1>Trello Landing Page</h1>
<%= link_to 'My Trello', controller: 'postits' %>
<%# style it here%>